(function(){
 const G=[
  {terms:['détecteur','detecteur','fumée','fumee','monoxyde'],title:'Vérifier / remplacer la batterie du détecteur',time:'10 min',difficulty:'Facile',materials:['Batterie compatible avec le détecteur','Escabeau au besoin','Chiffon sec'],steps:['Repère le modèle et le type de batterie indiqué sur le détecteur ou dans sa fiche HomePilot.','Teste le détecteur avec le bouton TEST avant l’intervention.','Ouvre le compartiment et remplace la batterie par le type exact recommandé par le fabricant.','Referme le compartiment puis maintiens le bouton TEST jusqu’au signal sonore.','Vérifie la date de remplacement recommandée du détecteur lui-même.'],warning:'Pour un détecteur 120 V ou interconnecté, ne démonte pas le câblage si tu n’es pas qualifié. Suis toujours le manuel du fabricant.'},
  {terms:['gouttière','gouttiere'],title:'Nettoyer les gouttières',time:'30–90 min',difficulty:'Moyen',materials:['Gants','Petit outil/pelle à gouttière','Boyau d’arrosage','Échelle stable'],steps:['Choisis une journée sèche et stabilise correctement l’échelle.','Retire feuilles et débris sans pousser les amas dans les descentes.','Rince doucement vers les descentes pluviales.','Vérifie que l’eau s’écoule librement et qu’aucun joint ne fuit.','Inspecte visuellement les fixations et la pente.'],warning:'Le travail en hauteur comporte un risque de chute. Si l’accès est difficile ou élevé, utilise un professionnel.'},
  {terms:['thermopompe','filtre'],title:'Nettoyer les filtres',time:'15–30 min',difficulty:'Facile',materials:['Aspirateur avec brosse douce','Eau tiède si le fabricant permet le lavage','Chiffon'],steps:['Éteins l’appareil.','Ouvre le panneau selon le manuel du fabricant.','Retire délicatement les filtres.','Aspire la poussière; lave seulement si le fabricant l’autorise.','Laisse sécher complètement avant de remettre les filtres.','Referme puis redémarre l’appareil.'],warning:'Les procédures varient selon la marque et le modèle. Le manuel du fabricant a priorité.'},
  {terms:['piscine'],title:'Entretien courant de la piscine',time:'20–40 min',difficulty:'Facile',materials:['Trousse d’analyse adaptée','Épuisette','Brosse','Produits prescrits pour ton système'],steps:['Retire les débris de surface.','Vérifie le niveau d’eau et la circulation.','Analyse l’eau avec une méthode compatible avec ton système.','Ajuste uniquement selon les résultats et les instructions inscrites sur les produits.','Brosse les surfaces et vérifie la pression/circulation du système.'],warning:'HomePilot ne remplace pas les dosages du fabricant. Pour les produits chimiques, l’étiquette et le manuel ont toujours priorité.'},
  {terms:['spa'],title:'Entretien courant du spa',time:'20–30 min',difficulty:'Facile',materials:['Trousse d’analyse adaptée','Produits recommandés par le fabricant','Chiffon/éponge non abrasive'],steps:['Vérifie le niveau d’eau et la circulation.','Analyse l’eau.','Ajuste les paramètres uniquement selon les instructions des produits utilisés.','Inspecte et nettoie le filtre selon le manuel.','Essuie la ligne d’eau et vérifie visuellement les composantes.'],warning:'Respecte toujours l’étiquette des produits et les recommandations du fabricant du spa.'}
 ];
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
 function guide(text){const t=norm(text);return G.find(g=>g.terms.filter(x=>x!=='filtre').some(x=>t.includes(norm(x))))||(t.includes('filtre')?G.find(g=>g.terms.includes('filtre')):null)}
 let opened=null;
 function productItems(g,context){
  const equipment=context.equipment,model=[equipment?.brand,equipment?.model].filter(Boolean).join(' ');
  return g.materials.map(material=>{
   if(material.startsWith('Eau tiède'))return {label:material,note:'À préparer à la maison, si le fabricant permet le lavage.',url:null};
   const compatible=/batterie|trousse|produits/i.test(material);
   const terms=[material,g.title.includes('piscine')?'piscine':g.title.includes('spa')?'spa':'',compatible?model:''].filter(Boolean).join(' ');
   const url=new URL('https://www.google.com/search');url.search=new URLSearchParams({tbm:'shop',hl:'fr',gl:'ca',q:terms}).toString();
   return {label:material,url:url.href,note:compatible?'Vérifie le type exact et la compatibilité avec ton équipement.':''};
  });
 }
 function modal(){if(document.getElementById('hpDiyModal'))return;const d=document.createElement('div');d.id='hpDiyModal';d.className='hidden';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.setAttribute('aria-label','Guide DIY');d.style='position:fixed;inset:0;z-index:100;background:#0008;padding:18px;overflow:auto';d.innerHTML='<div class="card" style="max-width:580px;margin:3vh auto"><div class="row"><h2>Guide DIY</h2><button type="button" class="alt" onclick="hpCloseDiy()">Fermer</button></div><div id="hpDiyBody"></div></div>';document.body.appendChild(d)}
 window.hpCloseDiy=()=>{document.getElementById('hpDiyModal')?.classList.add('hidden');opened=null};
 window.hpDiyContext=()=>opened?.context||null;
 window.hpOpenDiy=input=>{
  const context=window.hpProfessionalContext?window.hpProfessionalContext(input):typeof input==='string'?{text:input}:input;
  const g=guide(context?.text||context?.task?.title);if(!g)return;
  modal();opened={context,guide:g};
  const equipment=[context.equipment?.brand,context.equipment?.model].filter(Boolean).join(' ');
  document.getElementById('hpDiyBody').innerHTML=`<h2>${esc(g.title)}</h2><p class="muted">${esc(context.task?.title||context.text)}${context.property?.name?' · '+esc(context.property.name):''}${context.property?.city?' · '+esc(context.property.city):''}</p><div class="row" style="justify-content:flex-start"><span class="pill">⏱ ${esc(g.time)}</span><span class="pill">🛠 ${esc(g.difficulty)}</span></div><h3>Matériel nécessaire</h3><ul>${g.materials.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><button type="button" id="hpDiyProductsToggle" class="alt" style="width:100%;margin-bottom:12px" aria-expanded="false" aria-controls="hpDiyProducts">🛒 Trouver les produits</button><section id="hpDiyProducts" hidden><h3>Rechercher le matériel</h3><p class="muted">${equipment?'Équipement : '+esc(equipment)+'. ':''}Ces liens ouvrent une recherche d’achat. Vérifie la compatibilité, le prix et la disponibilité chez le marchand.</p>${productItems(g,context).map(item=>`<div class="card"><b>${esc(item.label)}</b>${item.note?'<p class="muted">'+esc(item.note)+'</p>':''}${item.url?`<a href="${esc(item.url)}" target="_blank" rel="noopener noreferrer" style="display:inline-block;padding:12px 0">Rechercher ce produit ↗</a>`:''}</div>`).join('')}</section><h3>Étapes</h3><ol>${g.steps.map(x=>'<li style="margin-bottom:10px">'+esc(x)+'</li>').join('')}</ol><div class="notice"><b>À vérifier avant d’agir</b><br>${esc(g.warning)}</div><button type="button" data-hp-diy-professional style="width:100%;margin-top:12px">👷 Trouver un professionnel</button>`;
  document.getElementById('hpDiyProductsToggle').onclick=()=>{const panel=document.getElementById('hpDiyProducts'),button=document.getElementById('hpDiyProductsToggle');panel.hidden=!panel.hidden;button.setAttribute('aria-expanded',String(!panel.hidden))};
  document.getElementById('hpDiyModal').classList.remove('hidden');
 };
 function enhance(){modal();for(const host of [document.getElementById('tl'),document.getElementById('at'),document.getElementById('tasklist')].filter(Boolean)){[...host.children].forEach(c=>{if(c.nodeType!==1||c.querySelector('.hpDiyBtn'))return;const title=c.querySelector('b')?.textContent||c.textContent||'';if(!guide(title))return;const b=document.createElement('button');b.type='button';b.className='alt hpDiyBtn';b.textContent='🛠 Guide DIY';b.style.marginTop='8px';b.onclick=()=>window.hpOpenDiy(window.hpProfessionalContextFromElement?window.hpProfessionalContextFromElement(c):title);c.appendChild(b)})}}
 function init(){enhance();new MutationObserver(()=>setTimeout(enhance,0)).observe(document.body,{childList:true,subtree:true})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setInterval(enhance,1500);
})();
