(function(){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function currentEquipment(){return typeof eq!=='undefined'?eq:(window.eqs||window.equipment||[])}
 function isDetector(e){const s=((e.equipment_type||'')+' '+(e.name||'')).toLowerCase();return s.includes('detect')||s.includes('fumée')||s.includes('fumee')||s.includes('co2')||s.includes('monoxyde')}
 function ensureModal(){if(document.getElementById('hpEqModal'))return;const m=document.createElement('div');m.id='hpEqModal';m.className='hidden';m.style='position:fixed;inset:0;z-index:90;background:#0007;padding:18px;overflow:auto';m.innerHTML='<div class="card" style="max-width:560px;margin:3vh auto"><div class="row"><h2>Fiche équipement</h2><button class="alt" onclick="hpCloseEq()">Fermer</button></div><div id="hpEqForm"></div></div>';document.body.appendChild(m)}
 window.hpCloseEq=()=>document.getElementById('hpEqModal')?.classList.add('hidden');
 window.hpOpenEq=id=>{ensureModal();const e=currentEquipment().find(x=>x.id===id);if(!e)return alert('Équipement introuvable.');const d=e.details||{};const battery=isDetector(e)?`<div class="notice" style="margin-top:12px"><b>🔋 Alimentation du détecteur</b></div><label>Type de batterie / pile</label><select id="heBattery"><option value="">Je ne sais pas</option>${['9 V','AA','AAA','CR123A','CR2','Pile lithium intégrée 10 ans','Électrique 120 V + batterie de secours','Autre'].map(v=>`<option value="${v}" ${d.battery_type===v?'selected':''}>${v}</option>`).join('')}</select><label>Référence exacte / format</label><input id="heBatteryRef" placeholder="Ex. Energizer 522, 9 V alcaline…" value="${esc(d.battery_reference||'')}"><label>Lien pour commander la bonne batterie</label><input id="heBatteryLink" type="url" placeholder="Sera utilisable pour un lien d’achat" value="${esc(d.battery_purchase_url||'')}"><p class="muted">HomePilot pourra éventuellement proposer directement la bonne batterie selon cette information.</p>`:'';document.getElementById('hpEqForm').innerHTML=`<div class="notice"><b>${esc(e.name||e.equipment_type)}</b><br>Conserve ici les références importantes de cet appareil.</div><label>Nom de l’équipement</label><input id="heName" value="${esc(e.name||'')}"><label>Marque</label><input id="heBrand" value="${esc(e.brand||d.brand||'')}"><label>Modèle</label><input id="heModel" value="${esc(e.model||d.model||'')}"><label>Numéro de série</label><input id="heSerial" value="${esc(e.serial_number||d.serial_number||'')}">${battery}<label>Date d’installation</label><input id="heInstalled" type="date" value="${esc(d.installation_date||'')}"><label>Installateur / fournisseur</label><input id="heInstaller" value="${esc(d.installer||'')}"><label>Fin de garantie</label><input id="heWarranty" type="date" value="${esc(d.warranty_expiry||'')}"><label>Dernier entretien</label><input id="heMaintenance" type="date" value="${esc(d.last_maintenance||'')}"><label>Lien vers le manuel</label><input id="heManual" type="url" placeholder="https://…" value="${esc(d.manual_url||'')}"><label>Lien vers facture / document</label><input id="heInvoice" type="url" placeholder="https://…" value="${esc(d.invoice_url||'')}"><label>Notes / historique</label><textarea id="heNotes" style="width:100%;min-height:100px;padding:12px;border:1px solid #d8e0dc;border-radius:12px">${esc(d.notes||'')}</textarea><div class="notice" style="margin:12px 0">📷 <b>Photos de plaque signalétique, factures et manuels</b><br>La structure de la fiche est prête. Le stockage sécurisé des fichiers sera ajouté avec le module Documents.</div><button style="width:100%" onclick="hpSaveEq('${e.id}')">Enregistrer la fiche</button>`;document.getElementById('hpEqModal').classList.remove('hidden')};
 window.hpSaveEq=async id=>{const e=currentEquipment().find(x=>x.id===id);if(!e)return;const details={...(e.details||{}),brand:heBrand.value.trim(),model:heModel.value.trim(),serial_number:heSerial.value.trim(),installation_date:heInstalled.value||null,installer:heInstaller.value.trim(),warranty_expiry:heWarranty.value||null,last_maintenance:heMaintenance.value||null,manual_url:heManual.value.trim(),invoice_url:heInvoice.value.trim(),notes:heNotes.value.trim()};if(isDetector(e)){details.battery_type=document.getElementById('heBattery')?.value||'';details.battery_reference=document.getElementById('heBatteryRef')?.value.trim()||'';details.battery_purchase_url=document.getElementById('heBatteryLink')?.value.trim()||''}const r=await sb.from('equipment').update({name:heName.value.trim()||e.name,brand:details.brand,model:details.model,serial_number:details.serial_number,details}).eq('id',id);if(r.error)return alert(r.error.message);e.name=heName.value.trim()||e.name;e.details=details;e.brand=details.brand;e.model=details.model;e.serial_number=details.serial_number;hpCloseEq();alert('Fiche équipement enregistrée.');if(typeof render==='function')render()};
 function enhance(){ensureModal();const list=document.getElementById('el');if(!list)return;for(const e of currentEquipment()){if(document.querySelector('[data-hpeq="'+e.id+'"]'))continue;const candidates=[...list.querySelectorAll('.card')];const card=candidates.find(c=>(c.textContent||'').includes(e.name||e.equipment_type));if(card){const b=document.createElement('button');b.className='alt';b.dataset.hpeq=e.id;b.textContent='📋 Voir la fiche';b.style.marginTop='8px';b.onclick=()=>hpOpenEq(e.id);card.appendChild(b)}}}
 const obs=new MutationObserver(()=>enhance());function init(){ensureModal();const list=document.getElementById('el');if(list)obs.observe(list,{childList:true,subtree:true});enhance()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setInterval(enhance,1200);
})();
