(function(){
 const $=id=>document.getElementById(id);
 const client=()=>window.supabaseClient||window.sb||window.client||null;
 const TYPES={snowmobile:'❄️ Motoneige',atv:'🛞 VTT',side_by_side:'🏔️ Côte-à-côte',boat:'🚤 Bateau',personal_watercraft:'🌊 Motomarine',rv:'🚐 VR / motorisé',travel_trailer:'🏕️ Roulotte',motorcycle:'🏍️ Moto',other:'🎯 Équipement'};
 const PRESETS={
  boat:[{title:'Mise en hiver du bateau',month:10,key:'boat_winterize'},{title:'Mise à l’eau et préparation de saison',month:5,key:'boat_spring'}],
  personal_watercraft:[{title:'Mise en hiver de la motomarine',month:10,key:'pwc_winterize'},{title:'Préparation de début de saison',month:5,key:'pwc_spring'}],
  snowmobile:[{title:'Préparation avant saison',month:11,key:'snowmobile_preseason'},{title:'Remisage de fin de saison',month:4,key:'snowmobile_storage'}],
  atv:[{title:'Entretien saisonnier du VTT',month:5,key:'atv_service'}],side_by_side:[{title:'Entretien saisonnier du côte-à-côte',month:5,key:'sxs_service'}],
  rv:[{title:'Hivernisation du VR',month:10,key:'rv_winterize'},{title:'Déshivernisation du VR',month:5,key:'rv_spring'}],
  travel_trailer:[{title:'Hivernisation de la roulotte',month:10,key:'trailer_winterize'},{title:'Préparation de la roulotte',month:5,key:'trailer_spring'}],
  motorcycle:[{title:'Remisage hivernal de la moto',month:10,key:'motorcycle_storage'},{title:'Inspection de début de saison',month:5,key:'motorcycle_spring'}]
 };
 const GUIDES={
  boat_winterize:{title:'Mise en hiver du bateau',steps:['Consulte le manuel du moteur et du bateau avant de commencer.','Stabilise le carburant si le fabricant le recommande et fais circuler le moteur selon la procédure prescrite.','Vidange ou protège les circuits d’eau contre le gel selon l’équipement.','Change l’huile moteur et/ou l’huile d’embase si le calendrier du fabricant l’exige.','Protège le système de refroidissement conformément au manuel; n’improvise pas avec un antigel non prévu pour cet usage.','Retire les objets humides, nettoie et sèche complètement l’intérieur.','Charge et entrepose la batterie selon les recommandations du fabricant.','Inspecte coque, hélice, anodes, remorque et pneus avant le remisage.','Couvre le bateau en laissant une ventilation suffisante.'],warning:'Les moteurs hors-bord, sterndrive et inboard n’ont pas la même procédure. Le manuel du fabricant a priorité. Si tu dois vidanger un bloc moteur ou manipuler du carburant, fais appel à un professionnel si tu n’es pas certain.'},
  boat_spring:{title:'Préparation du bateau',steps:['Retire la couverture et inspecte visuellement la coque.','Réinstalle et vérifie la batterie.','Contrôle les niveaux de fluides et les fuites.','Inspecte l’hélice, les anodes et les prises d’eau.','Teste pompe de cale, feux, klaxon et équipements de sécurité.','Vérifie la remorque, les roulements et la pression des pneus avant le transport.'],warning:'Ne démarre jamais un moteur refroidi par eau à sec.'},
  pwc_winterize:{title:'Mise en hiver de la motomarine',steps:['Lave et rince la coque et le circuit selon le manuel.','Stabilise le carburant si recommandé.','Protège le moteur et le circuit de refroidissement exactement selon la procédure du fabricant.','Inspecte la turbine et la grille d’admission.','Entretien la batterie puis entrepose la motomarine au sec.'],warning:'Les procédures varient fortement selon Sea-Doo, Yamaha et Kawasaki. Vérifie le manuel du modèle.'},
  snowmobile_preseason:{title:'Préparation de la motoneige',steps:['Inspecte chenille, glissières et tension.','Vérifie courroie, poulies et niveau d’huile.','Contrôle skis, lisses, suspension et freins.','Teste batterie, éclairage et arrêt d’urgence.','Vérifie la pression et l’état général selon le manuel.'],warning:'Une chenille mal ajustée ou un système de freinage défectueux doit être corrigé avant utilisation.'},
  snowmobile_storage:{title:'Remisage de la motoneige',steps:['Nettoie et sèche complètement la motoneige.','Traite le carburant selon les recommandations du fabricant.','Lubrifie les points prescrits.','Entretiens la batterie.','Relâche ou positionne la suspension comme recommandé et protège la machine de l’humidité.'],warning:'Suis le manuel du fabricant pour le système d’alimentation et le moteur.'},
  rv_winterize:{title:'Hivernisation du VR',steps:['Vidange complètement les réservoirs et le chauffe-eau selon le manuel.','Contourne le chauffe-eau si le système est prévu pour cela.','Souffle ou protège les conduites avec un antigel RV non toxique, selon la méthode du fabricant.','Protège pompes, valves, toilettes et drains.','Retire aliments et liquides sensibles au gel.','Vérifie batterie, propane, pneus et étanchéité.'],warning:'N’utilise jamais d’antigel automobile dans le réseau d’eau potable. Les appareils au propane nécessitent une attention particulière.'},
  trailer_winterize:{title:'Hivernisation de la roulotte',steps:['Vidange le réseau d’eau et le chauffe-eau.','Protège les conduites avec la méthode prescrite par le fabricant.','Nettoie réfrigérateur, armoires et drains.','Débranche ou entretiens la batterie.','Inspecte toit, joints, pneus et stabilisateurs.'],warning:'Utilise uniquement un antigel destiné aux systèmes d’eau potable de VR si requis.'},
  motorcycle_storage:{title:'Remisage de la moto',steps:['Nettoie et sèche la moto.','Traite le carburant selon le manuel.','Change l’huile si le calendrier d’entretien l’exige.','Entretiens la batterie avec un chargeur compatible.','Vérifie pression des pneus et protège la moto de l’humidité.'],warning:'Évite de faire tourner inutilement le moteur pendant l’hiver; suis la procédure du fabricant.'}
 };
 const fallbackGuide={title:'Entretien de l’équipement',steps:['Consulte le manuel du fabricant.','Inspecte l’équipement avant de commencer.','Effectue seulement les opérations pour lesquelles tu as les outils et les compétences.','Note les travaux réalisés et la date.'],warning:'Les procédures varient selon la marque et le modèle. Le manuel du fabricant a priorité.'};
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function fmt(v){if(!v)return'';return new Intl.DateTimeFormat('fr-CA',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v+'T12:00:00'))}
 async function me(){const c=client();if(!c)return null;const {data:{user}}=await c.auth.getUser();return user||null}
 function ensureModal(){if($('hpLeisureTaskModal'))return;const d=document.createElement('div');d.id='hpLeisureTaskModal';d.className='hidden';d.style='position:fixed;inset:0;z-index:150;background:#0009;padding:18px;overflow:auto';d.innerHTML='<div class="card" style="max-width:620px;margin:3vh auto"><div class="row"><h2 id="hpLtmTitle">Tâche loisir</h2><button class="alt" onclick="hpCloseLeisureTaskModal()">Fermer</button></div><div id="hpLtmBody"></div></div>';document.body.appendChild(d)}
 window.hpCloseLeisureTaskModal=()=>$('hpLeisureTaskModal')?.classList.add('hidden');
 function recommended(type){return PRESETS[type]||[]}
 function suggestedDate(month){const now=new Date(),y=now.getFullYear();let d=new Date(y,month-1,15);if(d<now)d=new Date(y+1,month-1,15);return d.toISOString().slice(0,10)}
 window.hpAddLeisureTask=(id,type,name)=>{ensureModal();const presets=recommended(type);$('hpLtmTitle').textContent='Ajouter une tâche';$('hpLtmBody').innerHTML=`<p class="muted">Pour <b>${esc(name)}</b></p>${presets.length?`<label>Tâche suggérée</label><select id="hpLtPreset"><option value="">Personnalisée</option>${presets.map((p,i)=>`<option value="${i}">${esc(p.title)}</option>`).join('')}</select>`:''}<label>Nom de la tâche</label><input id="hpLtTitle" placeholder="Ex. Mise en hiver"><label>Date</label><input id="hpLtDate" type="date"><label>Notes (facultatif)</label><input id="hpLtNotes"><button id="hpLtSave" style="width:100%">Ajouter la tâche</button>`;$('hpLeisureTaskModal').classList.remove('hidden');const sel=$('hpLtPreset');if(sel)sel.onchange=()=>{const p=presets[Number(sel.value)];if(p){$('hpLtTitle').value=p.title;$('hpLtDate').value=suggestedDate(p.month);$('hpLtSave').dataset.diy=p.key}else $('hpLtSave').dataset.diy=''};$('hpLtSave').onclick=()=>saveTask(id,type)};
 async function saveTask(equipmentId,type){const c=client(),user=await me();if(!c||!user)return;const title=$('hpLtTitle').value.trim();if(!title)return alert('Donne un nom à la tâche.');const preset=(PRESETS[type]||[]).find(p=>p.title===title);const {error}=await c.from('leisure_tasks').insert({user_id:user.id,leisure_equipment_id:equipmentId,title,due_date:$('hpLtDate').value||null,notes:$('hpLtNotes').value.trim()||null,diy_key:$('hpLtSave').dataset.diy||preset?.key||null});if(error)return alert(error.message);hpCloseLeisureTaskModal();hpLoadLeisure()}
 window.hpToggleLeisureTask=async(id,status)=>{const c=client();if(!c)return;const n=status==='done'?'todo':'done';await c.from('leisure_tasks').update({status:n,completed_at:n==='done'?new Date().toISOString():null}).eq('id',id);hpLoadLeisure()};
 window.hpDeleteLeisureTask=async id=>{if(!confirm('Supprimer cette tâche?'))return;const c=client();if(c){await c.from('leisure_tasks').delete().eq('id',id);hpLoadLeisure()}};
 window.hpShowLeisureDiy=key=>{ensureModal();const g=GUIDES[key]||fallbackGuide;$('hpLtmTitle').textContent='🛠 Guide DIY';$('hpLtmBody').innerHTML=`<h3>${esc(g.title)}</h3><div class="notice"><b>Avant de commencer</b><br>${esc(g.warning)}</div><h3>À faire</h3><ol>${g.steps.map(s=>`<li style="margin-bottom:10px">${esc(s)}</li>`).join('')}</ol><button style="width:100%;margin-top:10px" onclick="hpFindLeisurePro('${esc(key||'loisir')}')">👷 Trouver un professionnel</button>`;$('hpLeisureTaskModal').classList.remove('hidden')};
 window.hpFindLeisurePro=async key=>{ensureModal();const c=client();if(!c)return;const words=key.includes('boat')?'bateau marine nautique':key.includes('pwc')?'motomarine marine nautique':key.includes('snowmobile')?'motoneige':key.includes('rv')||key.includes('trailer')?'vr roulotte récréatif':key.includes('motorcycle')?'moto':'loisir';$('hpLtmTitle').textContent='👷 Professionnels';$('hpLtmBody').innerHTML='<p class="muted">Recherche dans le répertoire HomePilot…</p>';$('hpLeisureTaskModal').classList.remove('hidden');const {data,error}=await c.from('professional_profiles').select('id,business_name,phone,website,description,municipalities,regions,listing_tier,source,source_reference,rbq_license,imported_at,active,directory_issues').eq('active',true).limit(800);if(error){$('hpLtmBody').innerHTML='<div class="notice">Impossible de charger le répertoire.</div>';return}const terms=words.split(' '),rows=(data||[]).filter(p=>{const t=(p.business_name+' '+(p.description||'')).toLowerCase();return terms.some(w=>t.includes(w))}).slice(0,25);$('hpLtmBody').innerHTML=rows.length?rows.map(p=>window.hpProfessionalPresentation.card(p)).join(''):'<div class="card"><b>Aucun spécialiste loisir trouvé pour le moment.</b><p class="muted">Le répertoire résidentiel Québec-wide est déjà actif. Nous devrons maintenant ajouter les ateliers nautiques, concessionnaires et spécialistes de véhicules récréatifs au répertoire Loisirs.</p></div>'};
 async function renderLeisure(){const c=client(),user=await me();if(!c||!user||!$('hpLeisureList'))return;const [{data:eq,error:e1},{data:tasks,error:e2}]=await Promise.all([c.from('leisure_equipment').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),c.from('leisure_tasks').select('*').eq('user_id',user.id).order('due_date',{ascending:true})]);if(e1||e2)return;const rows=eq||[],ts=tasks||[];$('hpLeisureList').innerHTML=rows.length?rows.map(x=>{const own=ts.filter(t=>t.leisure_equipment_id===x.id),active=own.filter(t=>t.status!=='done');return `<div class="card"><div class="row"><div><b>${TYPES[x.equipment_type]||'🎯 Équipement'} · ${esc(x.name)}</b><div class="muted">${[x.brand,x.model,x.year].filter(Boolean).map(esc).join(' • ')}</div></div><button class="alt" onclick="hpDeleteLeisure('${x.id}')">Supprimer</button></div>${x.notes?`<p class="muted">${esc(x.notes)}</p>`:''}<div class="taskactions"><button onclick="hpAddLeisureTask('${x.id}','${x.equipment_type}','${esc(x.name)}')">+ Tâche</button><button class="alt" onclick="hpFindLeisurePro('${x.equipment_type}')">👷 Trouver un pro</button></div>${own.length?`<h4>Entretien & tâches</h4>${own.map(t=>`<div class="notice" style="margin:8px 0;opacity:${t.status==='done'?'.65':'1'}"><div class="row"><div><b>${t.status==='done'?'✓ ':''}${esc(t.title)}</b><div class="muted">${fmt(t.due_date)}</div></div><button class="alt" onclick="hpToggleLeisureTask('${t.id}','${t.status}')">${t.status==='done'?'Réouvrir':'Fait'}</button></div><div class="taskactions">${t.diy_key?`<button class="alt" onclick="hpShowLeisureDiy('${t.diy_key}')">🛠 Comment faire</button>`:''}<button class="alt" onclick="hpFindLeisurePro('${t.diy_key||x.equipment_type}')">👷 Professionnel</button><button class="alt" onclick="hpDeleteLeisureTask('${t.id}')">Supprimer</button></div></div>`).join('')}`:`<p class="muted">Aucune tâche. HomePilot peut te proposer l’entretien saisonnier.</p>${recommended(x.equipment_type).length?`<button class="alt" onclick="hpAddLeisureTask('${x.id}','${x.equipment_type}','${esc(x.name)}')">Ajouter une tâche saisonnière</button>`:''}`}</div>`}).join(''):'<div class="card muted">Aucun équipement de loisir pour le moment.</div>'}
 function init(){ensureModal();const wait=setInterval(()=>{if(window.hpLoadLeisure&&$('hpLeisureList')){clearInterval(wait);window.hpLoadLeisure=renderLeisure;renderLeisure()}},300)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();