(function(){
  const TYPES=[['snowmobile','❄️ Motoneige'],['atv','🛞 VTT'],['side_by_side','🏔️ Côte-à-côte'],['boat','🚤 Bateau'],['personal_watercraft','🌊 Motomarine'],['rv','🚐 VR / motorisé'],['travel_trailer','🏕️ Roulotte'],['motorcycle','🏍️ Moto'],['utility_trailer','🛻 Remorque'],['other','🎯 Autre']];
  const FACTS=[
    {title:'Le savais-tu?',body:'En 2026, le plafond annuel du CELI est de 7 000 $. Tes droits réels peuvent être plus élevés ou plus bas selon tes droits inutilisés, tes retraits et tes cotisations.',source:'Agence du revenu du Canada',url:'https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot/cotiser/calculer-droits.html'},
    {title:'Le savais-tu?',body:'Un retrait d’un CELI recrée des droits de cotisation seulement le 1er janvier de l’année suivante. Recotiser trop tôt peut créer une cotisation excédentaire.',source:'Agence du revenu du Canada',url:'https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot/retirer.html'}
  ];
  const $=id=>document.getElementById(id);
  function client(){return window.supabaseClient||window.sb||window.client||null}
  async function userAndHousehold(){const c=client();if(!c)return {};const {data:{user}}=await c.auth.getUser();if(!user)return {};const {data:m}=await c.from('household_members').select('household_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();return {user,householdId:m?.household_id||null}}
  async function householdProperties(householdId){const c=client();if(!c||!householdId)return [];const {data,error}=await c.from('properties').select('id,name,city').eq('household_id',householdId).order('created_at');if(error){console.error('Nuvabri budget properties',error);return []}return data||[]}
  function fixTabs(){const tabs=document.querySelector('.tabs>div');if(tabs)tabs.style.gridTemplateColumns='repeat(4,minmax(0,1fr))'}
  function ensureUI(){if($('leisure')||!document.querySelector('main.app')){fixTabs();return;}
    const main=document.querySelector('main.app');
    const leisure=document.createElement('section');leisure.id='leisure';leisure.className='screen';leisure.innerHTML=`<div class="row"><h2>Loisirs</h2><button onclick="hpToggleLeisureForm()">+ Équipement</button></div><p class="muted">Garde tes équipements de loisir au même endroit : motoneige, VTT, bateau, VR, roulotte, remorque et plus.</p><div id="hpLeisureForm" class="card hidden"><label>Type</label><select id="hpLeisureType">${TYPES.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><label>Nom</label><input id="hpLeisureName" placeholder="Ex. Expedition 900 Turbo R"><label>Marque</label><input id="hpLeisureBrand" placeholder="Ex. Ski-Doo"><label>Modèle</label><input id="hpLeisureModel"><label>Année</label><input id="hpLeisureYear" type="number" min="1900" max="2100"><label>Immatriculation (facultatif)</label><input id="hpLeisureRegistration"><label>Notes</label><input id="hpLeisureNotes" placeholder="Entretien, remisage, accessoires…"><button id="hpLeisureSave" style="width:100%">Ajouter</button><p id="hpLeisureSaveStatus" role="status" aria-live="polite"></p></div><div id="hpLeisureList"></div>`;
    const budget=document.createElement('section');budget.id='budget';budget.className='screen';budget.innerHTML=`<div class="row"><h2>Mes finances</h2><button id="hpBudgetAddBtn" onclick="hpToggleBudgetForm()">+ Entrée</button></div><div class="card season"><div class="badge">Finances</div><h3 id="hpFactTitle">Le savais-tu?</h3><p id="hpFactBody" class="muted"></p><a id="hpFactSource" target="_blank" rel="noopener" style="font-size:12px">Source officielle</a></div><div class="stats"><div><b id="hpIncome">0 $</b><br><span class="muted">Revenus notés</span></div><div><b id="hpExpense">0 $</b><br><span class="muted">Paiements notés</span></div><div><b id="hpBalance">0 $</b><br><span class="muted">Différence des opérations</span></div></div><div id="hpBudgetForm" class="card hidden"><h3>Noter un revenu ou un paiement</h3><p class="muted">Un montant réellement reçu ou payé, à la date de l’opération.</p><label>J’enregistre</label><select id="hpBudgetType"><option value="expense">Un paiement ou une cotisation</option><option value="income">Un revenu reçu</option></select><label>Catégorie</label><select id="hpBudgetCategory"><option>Maison</option><option>Épicerie</option><option>Transport</option><option>Loisirs</option><option>Assurances</option><option>Épargne</option><option>Salaire</option><option>Autre</option></select><label>Montant</label><input id="hpBudgetAmount" type="number" min="0" step="0.01"><label>Date</label><input id="hpBudgetDate" type="date"><label>Description</label><input id="hpBudgetDescription" placeholder="Ex. Essence motoneige"><label>Lier à une propriété (facultatif)</label><select id="hpBudgetProperty"><option value="">Aucune propriété</option></select><p class="muted" style="margin-top:-4px">Le budget fonctionne même sans propriété liée.</p><button id="hpBudgetSave" style="width:100%">Enregistrer cette opération</button><p id="hpBudgetStatus" class="muted"></p></div><h3>Ce mois-ci</h3><div id="hpBudgetList"></div><div class="notice" style="margin-top:12px">Les faits financiers sont informatifs. Vérifie tes droits personnels dans Mon dossier ARC avant de cotiser.</div>`;
    main.appendChild(leisure);main.appendChild(budget);
    $('hpLeisureSave').onclick=saveLeisure;$('hpBudgetSave').onclick=saveBudget;
    const d=new Date(),off=d.getTimezoneOffset();$('hpBudgetDate').value=new Date(d.getTime()-off*60000).toISOString().slice(0,10);
    showFact();
  }
  window.hpToggleLeisureForm=()=>$('hpLeisureForm')?.classList.toggle('hidden');
  window.hpToggleBudgetForm=async()=>{ensureUI();const f=$('hpBudgetForm');if(!f)return;const group=$('hpBudgetGroupMonthly');if(group)group.classList.add('open');const willOpen=f.classList.contains('hidden');if(willOpen){await populateBudgetProperties();f.classList.remove('hidden');setTimeout(()=>$('hpBudgetAmount')?.focus(),60);f.scrollIntoView({behavior:'smooth',block:'start'})}else f.classList.add('hidden')};
  function typeLabel(v){return TYPES.find(x=>x[0]===v)?.[1]||'🎯 Équipement'}
  let savingLeisure=false;
  async function saveLeisure(){
    if(savingLeisure)return;
    const btn=$('hpLeisureSave'),form=$('hpLeisureForm'),status=$('hpLeisureSaveStatus');
    const controls=[...form.querySelectorAll('input,select')];
    const message=text=>{if(status)status.textContent=text;else alert(text)};
    savingLeisure=true;btn.disabled=true;btn.textContent='Enregistrement…';controls.forEach(x=>x.disabled=true);if(status)status.textContent='';
    try{
      const name=$('hpLeisureName').value.trim(),type=$('hpLeisureType').value,year=$('hpLeisureYear').value===''?null:Number($('hpLeisureYear').value);
      if(!name)throw new Error('Donne un nom à l’équipement.');
      if(!TYPES.some(([key])=>key===type))throw new Error('Choisis un type de loisir.');
      if(year!==null&&(!Number.isInteger(year)||year<1900||year>2100))throw new Error('L’année doit être comprise entre 1900 et 2100.');
      const fields={equipment_type:type,name,brand:$('hpLeisureBrand').value.trim()||null,model:$('hpLeisureModel').value.trim()||null,year,registration:$('hpLeisureRegistration').value.trim()||null,notes:$('hpLeisureNotes').value.trim()||null};
      const {user,householdId}=await userAndHousehold(),c=client();if(!user||!c)throw new Error('Reconnecte-toi à Nuvabri.');
      const payload={...fields,user_id:user.id,household_id:householdId},key='leisure-create:'+user.id;
      payload.id=hpStability.operation(key,payload);
      const result=await c.from('leisure_equipment').upsert(payload,{onConflict:'id',ignoreDuplicates:true}).select('*');
      if(result.error)throw new Error('Enregistrement non confirmé. Réessaie sans changer les champs : la même fiche sera reprise.');
      let saved=result.data?.[0];
      if(!saved){const existing=await c.from('leisure_equipment').select('*').eq('id',payload.id).eq('user_id',user.id).maybeSingle();if(existing.error)throw new Error('Enregistrement non confirmé. Réessaie sans changer les champs.');saved=existing.data;}
      if(saved?.id!==payload.id||saved?.user_id!==user.id)throw new Error('La fiche n’a pas pu être confirmée. Réessaie.');
      const now=await c.auth.getUser();if(now.error||now.data?.user?.id!==user.id)return;
      hpStability.complete(key);form.classList.add('hidden');
      ['hpLeisureName','hpLeisureBrand','hpLeisureModel','hpLeisureYear','hpLeisureRegistration','hpLeisureNotes'].forEach(id=>$(id).value='');
      await hpLoadLeisure();
    }catch(error){message(error.message||'Impossible d’ajouter ce loisir. Réessaie.')}
    finally{savingLeisure=false;btn.disabled=false;btn.textContent='Ajouter';controls.forEach(x=>x.disabled=false);}
  }

  window.hpLoadLeisure=async()=>{ensureUI();const {user}=await userAndHousehold();const c=client();if(!user||!c)return;const {data,error}=await c.from('leisure_equipment').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(error)return;const rows=data||[];$('hpLeisureList').innerHTML=rows.length?rows.map(x=>`<div class="card"><div class="row"><div><b>${typeLabel(x.equipment_type)} · ${esc(x.name)}</b><div class="muted">${[x.brand,x.model,x.year].filter(Boolean).map(esc).join(' • ')}</div></div><button class="alt" onclick="hpDeleteLeisure('${x.id}')">Supprimer</button></div>${x.notes?`<p class="muted">${esc(x.notes)}</p>`:''}</div>`).join(''):'<div class="card muted">Aucun équipement de loisir pour le moment.</div>'}
  window.hpDeleteLeisure=async id=>{if(!confirm('Supprimer cet équipement?'))return;const c=client();if(c){await c.from('leisure_equipment').delete().eq('id',id);hpLoadLeisure()}}
  async function populateBudgetProperties(){const {householdId}=await userAndHousehold();const select=$('hpBudgetProperty');if(!select)return;const selected=select.value;const rows=await householdProperties(householdId);select.innerHTML='<option value="">Aucune propriété</option>'+rows.map(p=>`<option value="${p.id}">${esc(p.name)}${p.city?' — '+esc(p.city):''}</option>`).join('');if(selected&&rows.some(p=>p.id===selected))select.value=selected}
  async function saveBudget(){const status=$('hpBudgetStatus');if(status)status.textContent='';const {user,householdId}=await userAndHousehold();const c=client();if(!user||!c)return alert('Reconnecte-toi à Nuvabri.');const amount=Number($('hpBudgetAmount').value),entryDate=$('hpBudgetDate').value;if(!(amount>0))return alert('Entre un montant supérieur à 0.');if(!entryDate)return alert('Choisis une date.');const propertyId=$('hpBudgetProperty')?.value||null;const payload={user_id:user.id,household_id:householdId||null,property_id:propertyId,entry_type:$('hpBudgetType').value,category:$('hpBudgetCategory').value,amount,entry_date:entryDate,description:$('hpBudgetDescription').value.trim()||null};const btn=$('hpBudgetSave');if(btn)btn.disabled=true;const {error}=await c.from('budget_entries').insert(payload);if(btn)btn.disabled=false;if(error){console.error('Nuvabri budget save',error);if(status)status.textContent='Impossible d’enregistrer : '+error.message;return alert('Le budget n’a pas pu être enregistré.');}$('hpBudgetAmount').value='';$('hpBudgetDescription').value='';$('hpBudgetProperty').value='';$('hpBudgetForm').classList.add('hidden');await hpLoadBudget()}
  window.hpLoadBudget=async()=>{ensureUI();showFact();const {user}=await userAndHousehold();const c=client();if(!user||!c)return;await populateBudgetProperties();const now=new Date(),start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,end=new Date(now.getFullYear(),now.getMonth()+1,0),endS=`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}`;const {data,error}=await c.from('budget_entries').select('id,user_id,household_id,property_id,entry_type,category,amount,entry_date,description,properties(name)').eq('user_id',user.id).gte('entry_date',start).lte('entry_date',endS).order('entry_date',{ascending:false});if(error){console.error('Nuvabri budget load',error);return}const rows=data||[],inc=rows.filter(x=>x.entry_type==='income').reduce((a,x)=>a+Number(x.amount),0),exp=rows.filter(x=>x.entry_type==='expense').reduce((a,x)=>a+Number(x.amount),0);$('hpIncome').textContent=money(inc);$('hpExpense').textContent=money(exp);$('hpBalance').textContent=money(inc-exp);$('hpBudgetList').innerHTML=rows.length?rows.map(x=>`<div class="card row"><div><b>${x.entry_type==='income'?'＋':'−'} ${money(Number(x.amount))}</b><div class="muted">${esc(x.category)}${x.description?' • '+esc(x.description):''}${x.properties?.name?' • 🏠 '+esc(x.properties.name):''}<br>${new Intl.DateTimeFormat('fr-CA',{day:'numeric',month:'long'}).format(new Date(x.entry_date+'T12:00:00'))}</div></div><button class="alt" onclick="hpDeleteBudget('${x.id}')">×</button></div>`).join(''):'<div class="card muted">Aucune entrée pour ce mois.</div>'}
  window.hpDeleteBudget=async id=>{const c=client();if(c){await c.from('budget_entries').delete().eq('id',id);hpLoadBudget()}}
  function showFact(){if(!$('hpFactBody'))return;const f=FACTS[new Date().getDate()%FACTS.length];$('hpFactTitle').textContent=f.title;$('hpFactBody').textContent=f.body;$('hpFactSource').textContent=f.source;$('hpFactSource').href=f.url}
  function money(n){return new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(n)}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
  function init(){ensureUI();fixTabs();setTimeout(()=>{hpLoadLeisure();hpLoadBudget();fixTabs()},1800)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
