(function(){
  const TYPES=[['snowmobile','❄️ Motoneige'],['atv','🛞 VTT'],['side_by_side','🏔️ Côte-à-côte'],['boat','🚤 Bateau'],['personal_watercraft','🌊 Motomarine'],['rv','🚐 VR / motorisé'],['travel_trailer','🏕️ Roulotte'],['motorcycle','🏍️ Moto'],['other','🎯 Autre']];
  const FACTS=[
    {title:'Le savais-tu?',body:'En 2026, le plafond annuel du CELI est de 7 000 $. Tes droits réels peuvent être plus élevés ou plus bas selon tes droits inutilisés, tes retraits et tes cotisations.',source:'Agence du revenu du Canada',url:'https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot/cotiser/calculer-droits.html'},
    {title:'Le savais-tu?',body:'Un retrait d’un CELI recrée des droits de cotisation seulement le 1er janvier de l’année suivante. Recotiser trop tôt peut créer une cotisation excédentaire.',source:'Agence du revenu du Canada',url:'https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot/retirer.html'}
  ];
  const $=id=>document.getElementById(id);
  function client(){return window.supabaseClient||window.sb||window.client||null}
  async function userAndHousehold(){const c=client();if(!c)return {};const {data:{user}}=await c.auth.getUser();if(!user)return {};const {data:m}=await c.from('household_members').select('household_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();return {user,householdId:m?.household_id||null}}
  function ensureUI(){if($('leisure')||!document.querySelector('main.app'))return;
    const main=document.querySelector('main.app');
    const leisure=document.createElement('section');leisure.id='leisure';leisure.className='screen';leisure.innerHTML=`<div class="row"><h2>Loisirs</h2><button onclick="hpToggleLeisureForm()">+ Équipement</button></div><p class="muted">Garde tes équipements de loisir au même endroit : motoneige, VTT, bateau, VR, roulotte et plus.</p><div id="hpLeisureForm" class="card hidden"><label>Type</label><select id="hpLeisureType">${TYPES.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><label>Nom</label><input id="hpLeisureName" placeholder="Ex. Expedition 900 Turbo R"><label>Marque</label><input id="hpLeisureBrand" placeholder="Ex. Ski-Doo"><label>Modèle</label><input id="hpLeisureModel"><label>Année</label><input id="hpLeisureYear" type="number" min="1900" max="2100"><label>Immatriculation (facultatif)</label><input id="hpLeisureRegistration"><label>Notes</label><input id="hpLeisureNotes" placeholder="Entretien, remisage, accessoires…"><button id="hpLeisureSave" style="width:100%">Ajouter</button></div><div id="hpLeisureList"></div>`;
    const budget=document.createElement('section');budget.id='budget';budget.className='screen';budget.innerHTML=`<div class="row"><h2>Budget</h2><button onclick="hpToggleBudgetForm()">+ Entrée</button></div><div class="card season"><div class="badge">Finances</div><h3 id="hpFactTitle">Le savais-tu?</h3><p id="hpFactBody" class="muted"></p><a id="hpFactSource" target="_blank" rel="noopener" style="font-size:12px">Source officielle</a></div><div class="stats"><div><b id="hpIncome">0 $</b><br><span class="muted">Revenus</span></div><div><b id="hpExpense">0 $</b><br><span class="muted">Dépenses</span></div><div><b id="hpBalance">0 $</b><br><span class="muted">Solde</span></div></div><div id="hpBudgetForm" class="card hidden"><label>Type</label><select id="hpBudgetType"><option value="expense">Dépense</option><option value="income">Revenu</option></select><label>Catégorie</label><select id="hpBudgetCategory"><option>Maison</option><option>Épicerie</option><option>Transport</option><option>Loisirs</option><option>Assurances</option><option>Épargne</option><option>Salaire</option><option>Autre</option></select><label>Montant</label><input id="hpBudgetAmount" type="number" min="0" step="0.01"><label>Date</label><input id="hpBudgetDate" type="date"><label>Description</label><input id="hpBudgetDescription" placeholder="Ex. Essence motoneige"><button id="hpBudgetSave" style="width:100%">Ajouter au budget</button></div><h3>Ce mois-ci</h3><div id="hpBudgetList"></div><div class="notice" style="margin-top:12px">Les faits financiers sont informatifs. Vérifie tes droits personnels dans Mon dossier ARC avant de cotiser.</div>`;
    main.appendChild(leisure);main.appendChild(budget);
    const tabs=document.querySelector('.tabs>div');if(tabs){tabs.style.gridTemplateColumns='repeat(7,minmax(72px,1fr))';tabs.parentElement.style.overflowX='auto';tabs.style.minWidth='520px';tabs.insertAdjacentHTML('beforeend','<div class="tab" onclick="show(\'leisure\');hpLoadLeisure()">🎿<br>Loisirs</div><div class="tab" onclick="show(\'budget\');hpLoadBudget()">💰<br>Budget</div>')}
    $('hpLeisureSave').onclick=saveLeisure;$('hpBudgetSave').onclick=saveBudget;
    const d=new Date(),off=d.getTimezoneOffset();$('hpBudgetDate').value=new Date(d.getTime()-off*60000).toISOString().slice(0,10);
    showFact();
  }
  window.hpToggleLeisureForm=()=>$('hpLeisureForm')?.classList.toggle('hidden');
  window.hpToggleBudgetForm=()=>$('hpBudgetForm')?.classList.toggle('hidden');
  function typeLabel(v){return TYPES.find(x=>x[0]===v)?.[1]||'🎯 Équipement'}
  async function saveLeisure(){const {user,householdId}=await userAndHousehold();const c=client();if(!user||!c)return alert('Reconnecte-toi à HomePilot.');const name=$('hpLeisureName').value.trim();if(!name)return alert('Donne un nom à l’équipement.');const payload={user_id:user.id,household_id:householdId,equipment_type:$('hpLeisureType').value,name,brand:$('hpLeisureBrand').value.trim()||null,model:$('hpLeisureModel').value.trim()||null,year:$('hpLeisureYear').value?+$('hpLeisureYear').value:null,registration:$('hpLeisureRegistration').value.trim()||null,notes:$('hpLeisureNotes').value.trim()||null};const {error}=await c.from('leisure_equipment').insert(payload);if(error)return alert(error.message);$('hpLeisureForm').classList.add('hidden');['hpLeisureName','hpLeisureBrand','hpLeisureModel','hpLeisureYear','hpLeisureRegistration','hpLeisureNotes'].forEach(id=>$(id).value='');await hpLoadLeisure()}
  window.hpLoadLeisure=async()=>{ensureUI();const {user}=await userAndHousehold();const c=client();if(!user||!c)return;const {data,error}=await c.from('leisure_equipment').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(error)return;const rows=data||[];$('hpLeisureList').innerHTML=rows.length?rows.map(x=>`<div class="card"><div class="row"><div><b>${typeLabel(x.equipment_type)} · ${esc(x.name)}</b><div class="muted">${[x.brand,x.model,x.year].filter(Boolean).map(esc).join(' • ')}</div></div><button class="alt" onclick="hpDeleteLeisure('${x.id}')">Supprimer</button></div>${x.notes?`<p class="muted">${esc(x.notes)}</p>`:''}</div>`).join(''):'<div class="card muted">Aucun équipement de loisir pour le moment.</div>'}
  window.hpDeleteLeisure=async id=>{if(!confirm('Supprimer cet équipement?'))return;const c=client();if(c){await c.from('leisure_equipment').delete().eq('id',id);hpLoadLeisure()}}
  async function saveBudget(){const {user,householdId}=await userAndHousehold();const c=client();if(!user||!c)return alert('Reconnecte-toi à HomePilot.');const amount=Number($('hpBudgetAmount').value);if(!(amount>0))return alert('Entre un montant supérieur à 0.');const payload={user_id:user.id,household_id:householdId,entry_type:$('hpBudgetType').value,category:$('hpBudgetCategory').value,amount,entry_date:$('hpBudgetDate').value,description:$('hpBudgetDescription').value.trim()||null};const {error}=await c.from('budget_entries').insert(payload);if(error)return alert(error.message);$('hpBudgetAmount').value='';$('hpBudgetDescription').value='';$('hpBudgetForm').classList.add('hidden');await hpLoadBudget()}
  window.hpLoadBudget=async()=>{ensureUI();showFact();const {user}=await userAndHousehold();const c=client();if(!user||!c)return;const now=new Date(),start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,end=new Date(now.getFullYear(),now.getMonth()+1,0),endS=`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}`;const {data,error}=await c.from('budget_entries').select('*').eq('user_id',user.id).gte('entry_date',start).lte('entry_date',endS).order('entry_date',{ascending:false});if(error)return;const rows=data||[],inc=rows.filter(x=>x.entry_type==='income').reduce((a,x)=>a+Number(x.amount),0),exp=rows.filter(x=>x.entry_type==='expense').reduce((a,x)=>a+Number(x.amount),0);$('hpIncome').textContent=money(inc);$('hpExpense').textContent=money(exp);$('hpBalance').textContent=money(inc-exp);$('hpBudgetList').innerHTML=rows.length?rows.map(x=>`<div class="card row"><div><b>${x.entry_type==='income'?'＋':'−'} ${money(Number(x.amount))}</b><div class="muted">${esc(x.category)}${x.description?' • '+esc(x.description):''}<br>${new Intl.DateTimeFormat('fr-CA',{day:'numeric',month:'long'}).format(new Date(x.entry_date+'T12:00:00'))}</div></div><button class="alt" onclick="hpDeleteBudget('${x.id}')">×</button></div>`).join(''):'<div class="card muted">Aucune entrée pour ce mois.</div>'}
  window.hpDeleteBudget=async id=>{const c=client();if(c){await c.from('budget_entries').delete().eq('id',id);hpLoadBudget()}}
  function showFact(){if(!$('hpFactBody'))return;const f=FACTS[new Date().getDate()%FACTS.length];$('hpFactTitle').textContent=f.title;$('hpFactBody').textContent=f.body;$('hpFactSource').textContent=f.source;$('hpFactSource').href=f.url}
  function money(n){return new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(n)}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function init(){ensureUI();setTimeout(()=>{hpLoadLeisure();hpLoadBudget()},1800)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();