(function(){
 const norm=s=>(s||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 const cleanHeader=s=>norm(s).replace(/[^a-z0-9]/g,'');
 const H={license:['numerodelicence','noLicence','licence'],status:['statutdelalicence','statutlicence'],type:['typedelicence','typelicence'],email:['courriel'],address:['adresse'],neq:['neq'],name:['nomdelintervenant','nomintervenant','nom'],phone:['numerodetelephone','telephone'],city:['municipalite'],region:['regionadministrative'],categories:['categoriesetsouscategories','categorieetsouscategorie','souscategories'],other:['autrenom']};
 function col(headers,keys){for(const k of keys){const i=headers.indexOf(k);if(i>=0)return i}return -1}
 function parseCSV(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))out.push(row);return out}
 function cat(text){const t=norm(text);if(/electric|cmeq|16\.|16\s/.test(t))return'electrical';if(/plomb|tuyaut|chauffage|gaz|15\.|15\s/.test(t))return'plumbing';if(/ventilation|climatisation|thermopompe|refrigeration|hvac/.test(t))return'hvac';if(/toiture|couverture|goutti/.test(t))return'roofing';if(/cheminee|ramon/.test(t))return'chimney';if(/piscine|spa/.test(t))return'pool_spa';if(/fosse|septique/.test(t))return'septic';return'general'}
 function record(row,idx){const v=k=>{const i=idx[k];return i>=0?(row[i]||'').trim():''};const categories=v('categories');const license=v('license');return {business_name:v('name')||v('other'),category:cat(categories),phone:v('phone')||null,email:v('email')||null,website:null,neq:v('neq')||null,regions:v('region')?[v('region')]:[],municipalities:v('city')?[v('city')]:[],postal_prefixes:[],serves_all_quebec:false,verification_status:'verified',listing_tier:'organic',country_code:'CA',province_code:'QC',active:true,description:'Entrepreneur titulaire d’une licence active de la Régie du bâtiment du Québec. Catégories RBQ: '+(categories||'non précisées'),source:'RBQ_CC_BY_4_0',source_reference:license?('Licence RBQ '+license):'Données ouvertes RBQ',imported_at:new Date().toISOString()}}
 async function allowed(){const c=window.sb||window.supabaseClient||window.client;if(!c)return false;const {data:{user}}=await c.auth.getUser();if(!user)return false;const {data}=await c.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !!data}
 async function importRows(rows,status){const c=window.sb||window.supabaseClient||window.client;if(!c)return;if(!(await allowed())){status.textContent='Accès administrateur requis.';return}let ok=0,fail=0;for(let i=0;i<rows.length;i+=100){const batch=rows.slice(i,i+100);const withNeq=batch.filter(x=>x.neq),without=batch.filter(x=>!x.neq);if(withNeq.length){const {error}=await c.from('professional_profiles').upsert(withNeq,{onConflict:'neq'});error?fail+=withNeq.length:ok+=withNeq.length}if(without.length){const {error}=await c.from('professional_profiles').insert(without);error?fail+=without.length:ok+=without.length}status.textContent=`Import RBQ… ${Math.min(i+100,rows.length)}/${rows.length}`;}status.textContent=`✓ ${ok} entrepreneur(s) RBQ enregistré(s) (les fiches incomplètes restent masquées)${fail?' • '+fail+' erreur(s)':''}.`}
 function ui(){if(document.getElementById('hpRbqImport'))return;const admin=document.getElementById('hpAdminPros')||document.querySelector('[data-homepilot-admin]');if(!admin)return;const box=document.createElement('div');box.id='hpRbqImport';box.className='card';box.innerHTML='<h3>🏗 Import officiel RBQ</h3><p class="muted">Importe directement le CSV des licences actives de la Régie du bâtiment du Québec. Nuvabri détecte automatiquement le nom, NEQ, téléphone, courriel, municipalité, région et catégories de licence.</p><div class="notice"><b>Source recommandée</b><br>Liste des licences actives de la RBQ — Données Québec — licence CC BY 4.0. Conserve l’attribution à la RBQ dans Nuvabri.</div><input id="hpRbqFile" type="file" accept=".csv,text/csv" style="margin-top:10px"><div id="hpRbqPreview" class="muted"></div><button id="hpRbqGo" class="hidden" style="width:100%;margin-top:10px">Importer les entrepreneurs RBQ</button><p id="hpRbqStatus" class="muted"></p>';admin.prepend(box);let ready=[];box.querySelector('#hpRbqFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const rows=parseCSV(await f.text());if(rows.length<2)return;const headers=rows.shift().map(cleanHeader);const idx={};for(const k of Object.keys(H))idx[k]=col(headers,H[k].map(cleanHeader));ready=rows.map(r=>record(r,idx)).filter(x=>x.business_name);box.querySelector('#hpRbqPreview').textContent=`${ready.length} licence(s) lisible(s). Les entreprises seront dédupliquées par NEQ.`;box.querySelector('#hpRbqGo').classList.toggle('hidden',!ready.length)};box.querySelector('#hpRbqGo').onclick=()=>importRows(ready,box.querySelector('#hpRbqStatus'))}
 function init(){ui();new MutationObserver(ui).observe(document.body,{childList:true,subtree:true});setInterval(ui,1500)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();