import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function setup(){const c=vm.createContext({structuredClone,AbortSignal,document:{readyState:'loading',addEventListener(){}}});c.window=c;for(const f of ['budget-engine.js','budget-catalog.js','budget-insights.js','budget-entry-options.js'])vm.runInContext(readFileSync(new URL('../'+f,import.meta.url),'utf8'),c);return c}
const entry={user_id:'owner',request_id:'a',property_id:'house',entry_type:'expense',category:'Téléphone',description:'Téléphone',amount:50,entry_date:'2026-09-15'};
test('income and expense categories are distinct and alphabetic',()=>{const c=setup(),income=c.hpBudgetCatalog.categoriesFor('income'),expense=c.hpBudgetCatalog.categoriesFor('expense');assert.ok(income.includes('Salaire'));assert.ok(!expense.includes('Salaire'));assert.ok(!income.includes('Épicerie'));for(const list of [income,expense])assert.equal(JSON.stringify(list),JSON.stringify([...list].sort(c.hpBudgetCatalog.alphabetical)))});
test('recurring payments deduplicate retries and later payments without merging properties',()=>{const c=setup(),build=c.hpBuildRecurringEntryPlan;let p=build(null,entry,'weekly').config;assert.equal(p.bills.length,1);assert.ok(build(p,entry,'weekly').unchanged);assert.ok(build(p,{...entry,request_id:'b',entry_date:'2026-09-22'},'weekly').unchanged);p=build(p,{...entry,request_id:'c',property_id:'other-house'},'weekly').config;assert.equal(p.bills.length,2);assert.equal(p.bills[0].amount,50)});
test('pay frequencies create forecast income on the correct dates',()=>{const c=setup();for(const [frequency,count] of [['weekly',5],['biweekly',3],['monthly',1]]){const p=c.hpBuildRecurringEntryPlan(null,{...entry,entry_type:'income',category:'Salaire',description:'Paie',entry_date:'2026-09-01'},frequency).config;assert.equal(c.hpBudgetEngine.occurrences(p.incomes[0],'2026-09-01','2026-09-30').length,count);assert.equal(p.bills.length,0)}});
function savings(c,overrides={}){const p=c.hpBudgetEngine.empty();p.bills.push({id:'s',label:'CELI',category:'CELI',amount:100,frequency:'monthly',anchorDate:'2026-09-15',accountBalance:1000,accountBalanceAsOf:'2026-09-15',...overrides});return p}
test('dated savings excludes deposits already in the balance and projects twelve anniversaries',()=>{const c=setup(),p=savings(c);let a=c.hpBudgetInsights.monthlySavings(p,'2026-09-15')[0];assert.equal(a.currentEstimate,100000);assert.equal(a.points[0].date,'2026-10-15');assert.equal(a.points[0].balance,110000);assert.equal(a.points[11].balance,220000);assert.equal(c.hpBudgetInsights.monthlySavings(p,'2026-10-15')[0].currentEstimate,110000);assert.equal(c.hpBudgetEngine.validate(p).bills[0].accountBalanceAsOf,'2026-09-15')});
test('savings handles missing dates, zero balances, leap dates and older baselines',()=>{const c=setup();assert.equal(c.hpBudgetInsights.monthlySavings(savings(c,{accountBalanceAsOf:null}),'2026-09-15')[0].currentEstimate,null);assert.equal(c.hpBudgetInsights.monthlySavings(savings(c,{accountBalance:0}),'2026-09-15')[0].currentEstimate,0);let a=c.hpBudgetInsights.monthlySavings(savings(c,{accountBalanceAsOf:'2024-01-31',anchorDate:'2024-01-31'}),'2026-09-15')[0];assert.equal(a.points[0].date,'2024-02-29');assert.equal(a.currentEstimate,410000)});
test('recurrence commits use revision protection and reject an owner change',async()=>{const c=setup();let owner='owner',calls=[];c.supabaseClient={auth:{getSession:async()=>({data:{session:{user:{id:owner}}}})}};c.hpStability={operation:()=> 'id',complete(){}};c.fetch=async(url,o)=>{calls.push(o);return {ok:true,json:async()=>o.method==='GET'?{config:c.hpBudgetEngine.empty(),revision:'old'}:{ok:true,revision:'new'}}};const save=await c.hpPrepareEntryRecurrence(entry,'weekly','token');await save();assert.equal(JSON.parse(calls[1].body).expected_revision,'old');const other=await c.hpPrepareEntryRecurrence(entry,'monthly','token');owner='other';await assert.rejects(other,/session a changé/);assert.equal(calls.length,3)});
test('entry UI switches category menus and reveals recurrence without clearing the amount',()=>{
 const c=setup(),nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{id,value:'',dataset:{},checked:false,replaceChildren(...children){this.children=children},querySelector(){return node('title')}});return nodes.get(id)};
 for(const id of ['hpBudgetType','hpBudgetCategory','hpBudgetForm','hpBudgetRepeat','hpBudgetRepeatLabel','hpBudgetRepeatFields','hpBudgetAmount'])node(id);
 c.document.getElementById=id=>nodes.get(id);c.document.createElement=()=>({});node('hpBudgetAmount').value='500';node('hpBudgetType').value='income';node('hpBudgetCategory').value='Épicerie';c.hpSyncBudgetEntryOptions();assert.equal(node('hpBudgetCategory').value,'Salaire');assert.equal(node('title').textContent,'Ajouter un revenu');assert.equal(node('hpBudgetRepeatFields').hidden,true);
 node('hpBudgetRepeat').checked=true;c.hpSyncBudgetEntryOptions();assert.equal(node('hpBudgetRepeatFields').hidden,false);node('hpBudgetType').value='expense';c.hpSyncBudgetEntryOptions();assert.equal(node('hpBudgetCategory').value,'Autre');assert.equal(node('title').textContent,'Ajouter une dépense');assert.equal(node('hpBudgetAmount').value,'500');c.hpResetBudgetEntryOptions();assert.equal(node('hpBudgetRepeatFields').hidden,true);
});
